import { Store } from "./store.js";
import { UserProfile } from "./types.js";
import fs from "fs";
import path from "path";
import os from "os";

const DISLIKE_PATTERNS = [
  "不要用", "不要使用", "别用", "不需要", "我不喜欢",
  "don't use", "don't want", "i hate", "no need for", "avoid using",
];

const PREFERENCE_PATTERNS = [
  "我喜欢", "我习惯", "我通常", "我偏好", "我更愿意",
  "i prefer", "i like", "i usually", "i always use", "my preference",
];

const DECISION_PATTERNS = [
  "决定用", "选择了", "确定用", "最终选了",
  "decided to use", "chose", "going with", "we'll use",
];

export class Profiler {
  private store: Store;
  private cachedProfiles = new Map<string, UserProfile>();
  private lastRefresh = new Map<string, number>();
  private lastProcessedConvId = new Map<string, number>();
  private lastProcessedFileId = new Map<string, number>();

  constructor(store: Store) {
    this.store = store;
  }

  async getProfile(project?: string): Promise<UserProfile> {
    const key = project || "__global__";
    const lastRefresh = this.lastRefresh.get(key) || 0;
    if (Date.now() - lastRefresh < 30000) {
      const cached = this.cachedProfiles.get(key);
      if (cached) return cached;
    }
    const profile = await this.buildProfile(project);
    this.cachedProfiles.set(key, profile);
    this.lastRefresh.set(key, Date.now());
    return profile;
  }

  async refreshProfile(project?: string): Promise<void> {
    await this.extractMemories(project);
    const profile = await this.buildProfile(project);
    const key = project || "__global__";
    this.cachedProfiles.set(key, profile);
    this.lastRefresh.set(key, Date.now());
    await this.updateAgentsMd(profile);
  }

  private async updateAgentsMd(profile: UserProfile): Promise<void> {
    const configDir = process.env.HINDSIGHT_CONFIG_DIR || path.join(os.homedir(), ".config", "opencode");
    if (!fs.existsSync(configDir)) {
      fs.mkdirSync(configDir, { recursive: true });
    }
    const agentsMdPath = path.join(configDir, "AGENTS.md");

    let existingContent = "";
    if (fs.existsSync(agentsMdPath)) {
      existingContent = fs.readFileSync(agentsMdPath, "utf-8");
    }

    let hindsightSection = `\n\n<!-- HINDSIGHT_START -->\n`;
    hindsightSection += `## User Profile (Auto-generated by Hindsight)\n\n`;
    hindsightSection += `> Last updated: ${new Date(profile.lastUpdated).toLocaleString()}\n\n`;

    if (Object.keys(profile.preferences).length > 0) {
      hindsightSection += `### Preferences\n\n`;
      for (const [key, value] of Object.entries(profile.preferences)) {
        hindsightSection += `- **${key}**: ${value}\n`;
      }
      hindsightSection += `\n`;
    }

    if (Object.keys(profile.patterns).length > 0) {
      hindsightSection += `### Patterns\n\n`;
      for (const [key, value] of Object.entries(profile.patterns)) {
        hindsightSection += `- **${key}**: ${value}\n`;
      }
      hindsightSection += `\n`;
    }

    if (profile.recentContext.length > 0) {
      hindsightSection += `### Recent Context\n\n`;
      for (const ctx of profile.recentContext) {
        hindsightSection += `#### ${ctx.area}\n`;
        hindsightSection += `Files: ${ctx.files.join(", ")}\n`;
        hindsightSection += `Changes: ${ctx.changes.join(", ")}\n\n`;
      }
    }

    hindsightSection += `<!-- HINDSIGHT_END -->\n`;

    const cleanedContent = existingContent.replace(
      /<!-- HINDSIGHT_START -->[\s\S]*?<!-- HINDSIGHT_END -->\n?/g,
      ""
    ).trim();

    const finalContent = cleanedContent
      ? cleanedContent + hindsightSection
      : hindsightSection.trimStart();

    fs.writeFileSync(agentsMdPath, finalContent);
  }

  private async buildProfile(project?: string): Promise<UserProfile> {
    const memories = await this.store.getMemories(undefined, 10000, project);
    const recentFiles = await this.store.getRecentFileEvents(100, project);

    const preferences: Record<string, string> = {};
    const patterns: Record<string, string> = {};

    for (const m of memories) {
      const parsed = this.parseMemoryContent(m.content);
      if (!parsed) continue;

      if (m.type === "preference") {
        preferences[parsed.key] = parsed.value;
      }
      if (m.type === "pattern") {
        patterns[parsed.key] = parsed.value;
      }
    }

    const recentContext = this.extractRecentContext(recentFiles);

    return {
      preferences,
      patterns,
      recentContext,
      lastUpdated: Date.now(),
    };
  }

  private parseMemoryContent(content: string): { key: string; value: string } | null {
    const idx = content.indexOf(":");
    if (idx === -1) return null;
    const key = content.substring(0, idx).trim();
    const value = content.substring(idx + 1).trim();
    if (!key || !value) return null;
    return { key, value };
  }

  private async extractMemories(project?: string): Promise<void> {
    const projectKey = project || "__global__";
    const convId = this.lastProcessedConvId.get(projectKey) || 0;
    const fileId = this.lastProcessedFileId.get(projectKey) || 0;
    
    const conversations = await this.store.getConversationsAfter(convId, project);
    const fileEvents = await this.store.getFileEventsAfter(fileId, project);

    const newConvIds = await this.extractFromConversations(conversations, project);
    const newFileIds = await this.extractFromFileEvents(fileEvents, project);

    if (newConvIds.length > 0) {
      this.lastProcessedConvId.set(projectKey, Math.max(...newConvIds));
    }
    if (newFileIds.length > 0) {
      this.lastProcessedFileId.set(projectKey, Math.max(...newFileIds));
    }
  }

  private async extractFromConversations(
    conversations: { id?: number; role: string; content: string; timestamp: number }[],
    project?: string
  ): Promise<number[]> {
    const processedIds: number[] = [];

    for (const msg of conversations) {
      if (msg.role !== "user") continue;
      if (msg.id !== undefined) processedIds.push(msg.id);

      const content = msg.content.toLowerCase();

      if (this.matchesAny(content, DISLIKE_PATTERNS)) {
        await this.store.addMemory({ timestamp: Date.now(), type: "preference", content: `dislike: ${msg.content}`, confidence: 0.7, source: "conversation", project });
      }

      if (this.matchesAny(content, PREFERENCE_PATTERNS)) {
        await this.store.addMemory({ timestamp: Date.now(), type: "preference", content: `stated: ${msg.content}`, confidence: 0.9, source: "conversation", project });
      }

      if (this.matchesAny(content, DECISION_PATTERNS)) {
        await this.store.addMemory({ timestamp: Date.now(), type: "decision", content: msg.content, confidence: 0.8, source: "conversation", project });
      }
    }

    return processedIds;
  }

  private matchesAny(content: string, patterns: string[]): boolean {
    return patterns.some((p) => content.includes(p));
  }

  private async extractFromFileEvents(
    fileEvents: { id?: number; path: string; action: string; timestamp: number }[],
    project?: string
  ): Promise<number[]> {
    if (fileEvents.length === 0) return [];

    const processedIds = fileEvents
      .filter((e) => e.id !== undefined)
      .map((e) => e.id as number);

    const fileTypes = new Map<string, number>();
    for (const event of fileEvents) {
      const ext = event.path.split(".").pop() || "";
      if (ext) {
        fileTypes.set(ext, (fileTypes.get(ext) || 0) + 1);
      }
    }

    if (fileTypes.size > 0) {
      const sorted = [...fileTypes.entries()].sort((a, b) => b[1] - a[1]);
      const topTypes = sorted.slice(0, 3).map(([ext, count]) => `${ext}(${count})`).join(", ");
      const content = `primary_file_types: ${topTypes}`;
      await this.store.addMemory({ timestamp: Date.now(), type: "pattern", content, confidence: 0.6, source: "file_events", project });
    }

    const dirs = new Set<string>();
    for (const event of fileEvents) {
      const parts = event.path.split(/[\\/]/);
      if (parts.length > 1) {
        dirs.add(parts.slice(0, -1).join("/"));
      }
    }
    if (dirs.size > 0) {
      const content = `active_directories: ${[...dirs].slice(0, 5).join(", ")}`;
      await this.store.addMemory({ timestamp: Date.now(), type: "context", content, confidence: 0.5, source: "file_events", project });
    }

    return processedIds;
  }

  private extractRecentContext(
    fileEvents: { path: string; action: string; timestamp: number }[]
  ): { area: string; files: string[]; changes: string[] }[] {
    const recentFiles = fileEvents.slice(0, 20);
    const dirGroups = new Map<string, { path: string; action: string }[]>();

    for (const f of recentFiles) {
      const parts = f.path.split(/[\\/]/);
      const dir = parts.length > 1 ? parts.slice(0, -1).join("/") : "root";
      if (!dirGroups.has(dir)) {
        dirGroups.set(dir, []);
      }
      dirGroups.get(dir)!.push({ path: f.path, action: f.action });
    }

    const verbFor = (action: string): string => {
      switch (action) {
        case "create": return "created";
        case "delete": return "deleted";
        default: return "modified";
      }
    };

    const contexts: { area: string; files: string[]; changes: string[] }[] = [];
    for (const [dir, files] of dirGroups) {
      if (files.length >= 2) {
        contexts.push({
          area: dir,
          files: files.slice(0, 5).map((f) => f.path),
          changes: files.map((f) => `${f.path.split(/[\\/]/).pop()} ${verbFor(f.action)}`),
        });
      }
    }

    return contexts.slice(0, 3);
  }
}
